### ISSUE TITLE
How to use CSS animations?

### ISSUE THREAD

**Issue by htor** [luruke/barba.js#54]
I'm trying to implement a simple fade-out-fade-in transition using only CSS. The result is that the new container is faded in, but old one does not get faded out first, it just disappears and jumps to the `fade-in`. Any tips on how to achieve this with CSS?

Right:
![right-2](https://cloud.githubusercontent.com/assets/1709263/17810862/e889b39e-661f-11e6-8d00-61b7a8b26006.gif)

Wrong (my code):
![wrong](https://cloud.githubusercontent.com/assets/1709263/17810874/f16d1ad2-661f-11e6-8418-5721cba4933b.gif)

My transition:

    document.addEventListener("DOMContentLoaded", function() {
        var FadeTransition = Barba.BaseTransition.extend({
          start: function() {
            Promise
              .all([this.newContainerLoading, this.fadeOut()])
              .then(this.fadeIn.bind(this));
          },

          fadeOut: function() {
            $(this.oldContainer).toggleClass('fade-out');
          },
          fadeIn: function() {
            $(this.newContainer).toggleClass('fade-in');
            this.done();
          }
        });

        Barba.Pjax.getTransition = function() {
          return FadeTransition;
        };
    });

My CSS animations:

    .fade-out { animation: .7s fade-out ease forwards; }
    .fade-in { animation: .7s fade-in ease forwards; }

    @keyframes fade-out {
        from { opacity: 1; },
        to { opacity: 0; }
    }

    @keyframes fade-in {
        from { opacity: 0; },
        to { opacity: 1; }
    }

**Comment by luruke** [comment]
Hi @htor ,
thanks for the very detailed issue.

I think your issue is that `fadeOut` do not return a promise, so `fadeIn` is called immediately `newContainerLoading` is resolved.

You should rewrite your `fadeOut` as:
```javascript
fadeOut: function() {
    $(this.oldContainer).toggleClass('fade-out');

    return new Promise(function(resolve, reject) {
        window.setTimeout(function() {
           resolve();
        }, 700);
    });
},
```
The best way would be to use the event `onanimationend` instead of a  simple timeout.

I haven't tried but in this way everything should work, let me know :)

**Comment by htor** [comment]
Thanks a lot,

Got it to work now, by returning a promise, plus fixing my CSS. Had a comma after the `from` clause plus I needed to override the `fade-in` animation when the container has both animation classes set on it during the transition. Just hacked it with `!important`. Seems to work:

```css
.fade-out { animation: fade-out .5s ease forwards !important; }
.fade-in { animation: fade-in .5s ease forwards; }

@keyframes fade-out {
    from { opacity: 1; } /* no comma here */
    to { opacity: 0; }
}

@keyframes fade-in {
    from { opacity: 0; } /* no comma here */
    to { opacity: 1; }
}
```

Fade-out function:

```javascript
fadeOut: function() {
    $(this.oldContainer).toggleClass('fade-out');

    return new Promise(function(resolve, reject) {
        window.setTimeout(function() {
           resolve();
        }, 700);
    });
},
```
